# Generated by Django 4.0.4 on 2022-04-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='porch',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='street',
        ),
    ]
