# Generated by Django 4.0.4 on 2022-04-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_address_shippingaddress_flat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='tel',
        ),
    ]
