# Generated by Django 4.0.4 on 2022-04-15 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_fio_fullorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
