# Generated by Django 4.0.4 on 2022-04-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingaddress_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullOrder',
        ),
    ]
