# Generated by Django 4.0.4 on 2022-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_fullorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feedback',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
