# Generated by Django 4.0.4 on 2022-04-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feedback',
        ),
    ]
