# Generated by Django 4.0.4 on 2022-04-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='products',
        ),
    ]
