# Generated by Django 4.0.4 on 2022-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_shippingaddress_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
