# Generated by Django 4.0.4 on 2022-04-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
