# Generated by Django 4.0.4 on 2022-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_comments_email_comments_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='time',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
