# Generated by Django 4.0.4 on 2022-04-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_shippingaddress_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='contacts',
            field=models.CharField(default='whatsapp', max_length=80),
        ),
    ]
