# Generated by Django 4.0.4 on 2022-04-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_shippingaddress_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='time',
            field=models.CharField(default='Текущее время', max_length=80),
        ),
    ]
